### ISSUE TITLE
Chamber light cannot be controlled on Centauri Carbon

### ISSUE THREAD

**Issue by inventor7777** [danielcherubini/elegoo-homeassistant#150]
## System Information

version | core-2025.7.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
container_arch | aarch64
user | root
virtualenv | false
python_version | 3.13.3
os_name | Linux
os_version | 6.12.35-haos
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.5
Stage | running
Available Repositories | 2098
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 16.0
-- | --
update_channel | stable
supervisor_version | supervisor-2025.07.1
agent_version | 1.7.2
docker_version | 28.3.0
disk_total | 28.0 GB
disk_used | 8.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | green
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.5.1), Govee to MQTT Bridge (2025.04.13-17d43d72), Matter Server (8.0.0), Tailscale (0.25.0), File editor (5.8.0), InfluxDB (5.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 8
views | 13
mode | storage

</details>

<details><summary>MercedesME 2020</summary>

api_endpoint_reachable | ok
-- | --
websocket_connection_state | connected
cars_connected | 1
version | v0.27.0-beta.1

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), end0 (enabled, default, auto), hassio (disabled), docker0 (disabled), vethcbcc1b4 (disabled), veth384ecec (disabled), vetha18820b (disabled), vethb6def31 (disabled), veth0abdb7b (disabled), veth716288a (disabled), veth5d3ae8a (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), end0 (192.168.50.59/24), hassio (172.30.32.1/23), docker0 (172.30.232.1/23), vethcbcc1b4 (), veth384ecec (), vetha18820b (), vethb6def31 (), veth0abdb7b (), veth716288a (), veth5d3ae8a ()
ipv6_addresses | lo (::1/128), end0 (fd02:acf6:267:ee44:1d59:46d1:8e57:d525/64, fe80::2fae:62f4:ee52:8dc3/64), hassio (fe80::c6f:f7ff:fe35:d767/64), docker0 (fe80::d8bf:8eff:fee2:5f28/64), vethcbcc1b4 (fe80::5890:27ff:fe32:c4ea/64), veth384ecec (fe80::8c38:8aff:fe7e:d325/64), vetha18820b (fe80::878:dbff:fe91:d0b9/64), vethb6def31 (fe80::d86e:ff:fe5e:a589/64), veth0abdb7b (fe80::a8cf:54ff:fe81:1aca/64), veth716288a (fe80::f8ea:d3ff:fe2f:19cd/64), veth5d3ae8a (fe80::dc61:a0ff:fea6:a93e/64)
announce_addresses | 192.168.50.59, fd02:acf6:267:ee44:1d59:46d1:8e57:d525, fe80::2fae:62f4:ee52:8dc3

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 18, 2025 at 20:06
-- | --
current_recorder_run | July 10, 2025 at 09:10
estimated_db_size | 1795.02 MiB
database_engine | sqlite
database_version | 3.48.0

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/elegoo_printer/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The chamber light on my Centauri Carbon cannot be controlled by ElegooPrinter. The web ui works fine to control the light, however I think my printer has a different light setup than the first batch if my memory serves me well. Mine has a led strip on the top as opposed to the basic camera beam.

![Image](https://github.com/user-attachments/assets/e39b6094-7ee0-478c-94ed-7ad724925189)

### Reproduction steps

Try to control chamber light on Centauri Carbon through ElegooPrinter

### Debug logs

```text
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/elegoo_printer/light.py:97
integration: Elegoo Printer (documentation, issues)
First occurred: 12:03:53 (1 occurrence)
Last logged: 12:03:53

/config/custom_components/elegoo_printer/light.py:97: RuntimeWarning: coroutine 'ElegooPrinterClient.set_light_status' was never awaited self._elegoo_printer_client.set_light_status(light_status)
```

### Diagnostics dump

Same status as the other log

“ 2025-07-10 12:03:53.719 WARNING (MainThread) [py.warnings] /config/custom_components/elegoo_printer/light.py:97: RuntimeWarning: coroutine 'ElegooPrinterClient.set_light_status' was never awaited
  self._elegoo_printer_client.set_light_status(light_status”

**Comment by danielcherubini** [comment]
Ohhhhhh. I wondered when this would show up. 

Ok. This is easy

**Comment by inventor7777** [comment]
Forgot to mention that the pause/resume etc functions work normally, it’s just the light which is not (and the cover image which is in another issue I believe).

**Comment by danielcherubini** [comment]
Fixed in 
https://github.com/danielcherubini/elegoo-homeassistant/releases/tag/v1.4.2

**Comment by danielcherubini** [comment]
The issue was in here 
```/config/custom_components/elegoo_printer/light.py:97: RuntimeWarning: coroutine 'ElegooPrinterClient.set_light_status' was never awaited self._elegoo_printer_client.set_light_status(light_status)```

**Comment by inventor7777** [comment]
Okay I’m going to install it now thanks! Will report back shortly

**Comment by inventor7777** [comment]
Unfortunately it doesn’t seem to work. The switch updates status when I turn it on/off via the printer screen but I still cannot control it from Home Assistant. :(

**Comment by danielcherubini** [comment]
any logs?

Thats really weird

**Comment by inventor7777** [comment]
No logs that I can see. Just the usual “error getting image”

I see a traceback but that might be something else

![Image](https://github.com/user-attachments/assets/e43020cc-9026-43d8-ac4d-f8a8b8cd8830)

**Comment by inventor7777** [comment]
Do you think you should reopen this issue for now? The light control is still not working.


(Disregard as now fixed)

**Comment by HumanSkunk** [comment]
What was done to fix this? I have recently received mine and set it up. I can control the light from the printer itself which updates the status in Home Assistant but I am unable to control it when the printer is printing from HA. It seems to be fine when printer is idling. Perhaps some communication limit with the printer when printing? Seems like an odd limitation.

**Comment by inventor7777** [comment]
@HumanSkunk looks like a limitation from Elegoo’s side. If I try to control the light through the Elegoo Web UI, it says “modification failed”. So I think Elegoo needs to release a printer update to fix it.

**Comment by HumanSkunk** [comment]
@inventor7777 ok hopefully in the next update they fix it. Just have to get off my arse in the mean time to see how the print is going!

**Comment by inventor7777** [comment]
Haha lol do that! I may email Elegoo later today or tomorrow about it and see what they say

**Comment by djayfresh** [comment]
Just adding that this also doesn't work from the ElegooSlicer Device tab either. 

When looking at the websocket for the website. I noticed the command is sending this:

```
"Data": {
        "Cmd": 403,
        "Data": {
            "LightStatus": {
                "SecondLight": false,
                "RgbLight": [0, 0, 0]
            }
        },
        "RequestID": "9dcc09a500e4454daf9102ea22cf1f3c",
        "MainboardID": "",
        "TimeStamp": 1753308025112,
        "From": 1
}
```

But the response from the printer for light is:
```
"LightStatus": {
    "SecondLight": 1,
    "RgbLight": [0, 0, 0]
},
```

Maybe we just need to flip `false` and `true` to `0` and `1`. Not able to test now, but just seems like a possibility. 

Confirmed turning the light off at the printer updated: `"SecondLight": 0,`

**Comment by danielcherubini** [comment]
Thats what we do. The problem is obviously on elegoos side not ours since it doesn't work in their own web interface.

We send 0 and 1

**Comment by inventor7777** [comment]
This could be something to do with the updated lighting. If I remember correctly the first batch had that one weak light right next to the camera; later batches have dual lights bars on the top @djayfresh @danielcherubini 

I’m guessing Elegoo just didn’t fix the code properly for activation during printing.

**Comment by danielcherubini** [comment]
https://discord.com/channels/969282195552346202/1384784731991838810/1397248264029343865

I just opened their official discord and opened the support area and this is the first message of people complaining the lights busted. 

So my guess is as I said, it's not this integration, it's most likely firmware. 

Elegoo will fix it soon I'm positive.
