### ISSUE TITLE
Action "lights.turn_off/on" Toggles the Centauri Carbon Chamber Light rather than perform the desired action

### ISSUE THREAD

**Issue by Busted99** [danielcherubini/elegoo-homeassistant#278]
## System Information

version | core-2025.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
container_arch | aarch64
user | root
virtualenv | false
python_version | 3.13.7
os_name | Linux
os_version | 6.12.34-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.5
Stage | running
Available Repositories | 2333
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 16, 2026 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-12.ui.nabu.casa
certificate_status | ready
instance_id | [REDACTED]
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 16.2
-- | --
update_channel | stable
supervisor_version | supervisor-2025.10.0
agent_version | 1.7.2
docker_version | 28.3.3
disk_total | 28.5 GB
disk_used | 11.1 GB
nameservers | [REDACTED]
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | TasmoAdmin (0.32.2), File editor (5.8.0), Terminal & SSH (9.20.1), Mosquitto broker (6.5.2), RPC Shutdown (2.5), Matter Server (8.1.1), Z-Wave JS (0.27.0), Samba share (12.5.3)

</details>

<details><summary>keymaster</summary>

zwave_integration | unknown
-- | --
network_status | unavailable

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 5
views | 14
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), end0 (enabled, default, auto), docker0 (disabled), hassio (disabled), vethb713c92 (disabled), veth13c7b59 (disabled), veth9425114 (disabled), veth99be9b4 (disabled), vethd5369dc (disabled), veth43ef718 (disabled), veth7a05621 (disabled), vethb930c61 (disabled), vethf05ac88 (disabled), veth82982b8 (disabled), veth692acc1 (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), end0 [REDACTED], docker0 [REDACTED], hassio [REDACTED], vethb713c92 (), veth13c7b59 (), veth9425114 (), veth99be9b4 (), vethd5369dc (), veth43ef718 (), veth7a05621 (), vethb930c61 (), vethf05ac88 (), veth82982b8 (), veth692acc1 ()
ipv6_addresses | lo (::1/128), end0 [REDACTED], docker0 [REDACTED], hassio [REDACTED], vethb713c92 [REDACTED], veth13c7b59 [REDACTED], veth9425114 [REDACTED], veth99be9b4 [REDACTED], vethd5369dc [REDACTED], veth43ef718 [REDACTED], veth7a05621 [REDACTED], vethb930c61 [REDACTED], vethf05ac88 [REDACTED], veth82982b8 [REDACTED], veth692acc1 [REDACTED]
announce_addresses | [REDACTED], [REDACTED]

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 11, 2025 at 1:28 PM
-- | --
current_recorder_run | October 25, 2025 at 10:33 PM
estimated_db_size | 649.50 MiB
database_engine | sqlite
database_version | 3.49.2

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/elegoo_printer/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Light Actions (such as Turn On, Turn off and Toggle) all seem to perform the Toggle option.

This results in Automations that have undesired outcomes.

For instance, a routine that fires when going to sleep that turns off all lights on a floor of my home could instead toggle the chamber light of my Centauri Carbon ON.

### Reproduction steps

1. Go to Developer Tools
2. Go to Actions Tab
3. Select Lights.turn_off action
4. Select entity "Chamber Light" for Centauri Carbon
5. Push the Perform Action button.

If the Chamber light is OFF, it will turn ON even though the action was to specifically TURN OFF.

You can do the same thing by selecting the Lights.turn_on action when the chamber light is already ON and performing the Turn On action will Toggle it OFF.

<img width="1451" height="535" alt="Image" src="https://github.com/user-attachments/assets/d383e1e1-56b4-447d-857b-4e6e3f49aab1" />
<img width="1444" height="581" alt="Image" src="https://github.com/user-attachments/assets/dba8bd16-573f-4a49-b5ec-1fcb8716d7ef" />
<img width="576" height="401" alt="Image" src="https://github.com/user-attachments/assets/373369dc-c2a1-42b7-bf40-993b8721e507" />

### Debug logs

```text
2025-10-26 01:51:34.721 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration custom_icons which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-26 01:51:34.724 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-26 01:51:34.727 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration keymaster which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-26 01:51:34.729 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration elegoo_printer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-26 01:51:53.023 WARNING (MainThread) [homeassistant.components.roborock.coordinator] Using the cloud API for device [REDACTED]. This is not recommended as it can lead to rate limiting. We recommend making your vacuum accessible by your Home Assistant instance
2025-10-26 01:51:53.598 WARNING (MainThread) [homeassistant.components.roborock.coordinator] Using the cloud API for device [REDACTED]. This is not recommended as it can lead to rate limiting. We recommend making your vacuum accessible by your Home Assistant instance
2025-10-26 01:51:56.075 DEBUG (MainThread) [custom_components.elegoo_printer] CONFIGURATION {'brand': 'ELEGOO', 'camera_enabled': False, 'connection': '[REDACTED]', 'firmware': 'V1.1.46', 'id': '[REDACTED]', 'ip_address': '[REDACTED]', 'model': 'Centauri Carbon', 'name': 'Centauri Carbon', 'printer_type': 'fdm', 'protocol': 'V3.0.0', 'proxy_enabled': True, 'proxy_video_port': None, 'proxy_websocket_port': None}
2025-10-26 01:51:56.076 DEBUG (MainThread) [custom_components.elegoo_printer] Testing connectivity to printer: Centauri Carbon at [REDACTED]
2025-10-26 01:51:56.077 DEBUG (MainThread) [custom_components.elegoo_printer] Trying direct IP discovery for printer Centauri Carbon at [REDACTED]
2025-10-26 01:51:56.081 INFO (SyncWorker_6) [custom_components.elegoo_printer] Broadcasting for printer/proxy discovery...
2025-10-26 01:51:56.206 INFO (SyncWorker_6) [custom_components.elegoo_printer] Discovery response received from ('[REDACTED]', 3000)
2025-10-26 01:51:56.206 INFO (SyncWorker_6) [custom_components.elegoo_printer] Discovered: Centauri Carbon ([REDACTED])
2025-10-26 01:52:01.215 DEBUG (SyncWorker_6) [custom_components.elegoo_printer] Discovered 1 printer(s).
2025-10-26 01:52:01.219 DEBUG (MainThread) [custom_components.elegoo_printer] Printer is reachable. Starting proxy server.
2025-10-26 01:52:01.219 DEBUG (MainThread) [custom_components.elegoo_printer] Creating new proxy server instance (references: 1)
2025-10-26 01:52:01.221 DEBUG (MainThread) [custom_components.elegoo_printer] Registered printer [REDACTED] with new proxy server
2025-10-26 01:52:01.225 DEBUG (MainThread) [custom_components.elegoo_printer] Created dedicated proxy sessions: API, Video, File
2025-10-26 01:52:01.229 INFO (MainThread) [custom_components.elegoo_printer] Centralized HTTP/WebSocket Proxy running on http://[REDACTED]:3030
2025-10-26 01:52:01.234 INFO (MainThread) [custom_components.elegoo_printer] Centralized Video Proxy running on http://[REDACTED]:3031
2025-10-26 01:52:01.237 INFO (MainThread) [custom_components.elegoo_printer] Discovery Proxy listening on UDP port 3000
2025-10-26 01:52:01.237 INFO (MainThread) [custom_components.elegoo_printer] Centralized proxy server started successfully.
2025-10-26 01:52:01.237 DEBUG (MainThread) [custom_components.elegoo_printer] Calling get_printer with specific_printer: Centauri Carbon (MainboardID: [REDACTED])
2025-10-26 01:52:01.237 DEBUG (MainThread) [custom_components.elegoo_printer] Got proxy printer: Centauri Carbon (MainboardID: [REDACTED])
2025-10-26 01:52:01.239 DEBUG (MainThread) [custom_components.elegoo_printer] Connecting to printer: Centauri Carbon at [REDACTED] with proxy enabled True
2025-10-26 01:52:01.240 INFO (MainThread) [custom_components.elegoo_printer] Closing connection to printer
2025-10-26 01:52:01.240 INFO (MainThread) [custom_components.elegoo_printer] Connecting to printer: Centauri Carbon at [REDACTED] proxy_enabled: True
2025-10-26 01:52:01.282 INFO (MainThread) [custom_components.elegoo_printer] Client successfully connected to: Centauri Carbon, via proxy: True
2025-10-26 01:52:01.282 INFO (MainThread) [custom_components.elegoo_printer] Polling Started
2025-10-26 01:52:01.282 DEBUG (MainThread) [custom_components.elegoo_printer] No config changes needed for printer Centauri Carbon
2025-10-26 01:52:01.674 DEBUG (MainThread) [custom_components.elegoo_printer] Checking for firmware updates
2025-10-26 01:52:01.675 DEBUG (MainThread) [custom_components.elegoo_printer] Original firmware version: V1.1.46
2025-10-26 01:52:01.675 DEBUG (MainThread) [custom_components.elegoo_printer] Normalized firmware version: 1.1.46
2025-10-26 01:52:01.675 DEBUG (MainThread) [custom_components.elegoo_printer] Checking for firmware updates
2025-10-26 01:52:01.675 DEBUG (MainThread) [custom_components.elegoo_printer] URL: https://mms.chituiot.com/mainboardVersionUpdate/getInfo.do7
2025-10-26 01:52:01.675 DEBUG (MainThread) [custom_components.elegoo_printer] Params: {'machineType': 'ELEGOO Centauri Carbon', 'machineId': 0, 'version': '1.1.46', 'lan': 'en', 'firmwareType': 1}
2025-10-26 01:52:02.682 DEBUG (MainThread) [custom_components.elegoo_printer] Response status: 200
2025-10-26 01:52:02.684 DEBUG (MainThread) [custom_components.elegoo_printer] Response headers: {'content-type': 'application/json;charset=UTF-8', 'date': 'Sun, 26 Oct 2025 05:52:01 GMT', 'req-cost-time': '4', 'req-arrive-time': '1761457922587', 'resp-start-time': '1761457922592', 'x-envoy-upstream-service-time': '4', 'vary': 'Accept-Encoding', 'content-encoding': 'br', 'server': 'istio-envoy', 'transfer-encoding': 'chunked'}
2025-10-26 01:52:02.684 DEBUG (MainThread) [custom_components.elegoo_printer] Firmware update response: {'code': '000000', 'messages': None, 'data': {'update': False, 'version': None, 'packageUrl': None, 'firmwareType': 0, 'packageHash': None, 'updateStrategy': 0, 'log': None, 'timeMS': 0, 'dataInfoId': None}, 'success': True}
2025-10-26 01:52:02.684 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 1.402 seconds (success: True)
2025-10-26 01:52:06.882 DEBUG (MainThread) [custom_components.elegoo_printer] Adding 34 sensor entities
2025-10-26 01:52:06.927 DEBUG (MainThread) [custom_components.elegoo_printer] Adding 3 binary sensor entities
2025-10-26 01:52:06.931 DEBUG (MainThread) [custom_components.elegoo_printer] Adding 1 image entities
2025-10-26 01:52:06.933 DEBUG (MainThread) [custom_components.elegoo_printer] Adding 1 Camera entities
2025-10-26 01:52:06.938 DEBUG (MainThread) [custom_components.elegoo_printer] Adding 1 light entities
2025-10-26 01:52:06.940 DEBUG (MainThread) [custom_components.elegoo_printer] Adding 3 button entities
2025-10-26 01:52:07.274 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.391 seconds (success: True)
2025-10-26 01:52:09.357 ERROR (MainThread) [custom_components.keymaster.binary_sensor] Z-Wave integration not found
2025-10-26 01:52:09.357 WARNING (MainThread) [homeassistant.components.binary_sensor] Platform keymaster not ready yet: None; Retrying in background in 30 seconds
2025-10-26 01:52:09.550 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.940 seconds (success: True)
2025-10-26 01:52:10.828 ERROR (MainThread) [custom_components.keymaster.binary_sensor] Z-Wave integration not found
2025-10-26 01:52:12.218 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.729 seconds (success: True)
2025-10-26 01:52:13.966 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.471 seconds (success: True)
2025-10-26 01:52:15.855 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.371 seconds (success: True)
2025-10-26 01:52:17.917 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.437 seconds (success: True)
2025-10-26 01:52:19.807 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.325 seconds (success: True)
2025-10-26 01:52:21.796 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.314 seconds (success: True)
2025-10-26 01:52:22.527 DEBUG (MainThread) [custom_components.elegoo_printer] Sending printer video: {'status': <ElegooVideoStatus.SUCCESS: 0>, 'video_url': '[REDACTED]:3031/video'}
2025-10-26 01:52:22.528 DEBUG (MainThread) [custom_components.elegoo_printer] stream_source: Video is OK, getting stream source
2025-10-26 01:52:22.528 DEBUG (MainThread) [custom_components.elegoo_printer] stream_source: Using video url: http://[REDACTED]:3031/video
2025-10-26 01:52:24.128 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.647 seconds (success: True)
2025-10-26 01:52:25.837 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.356 seconds (success: True)
2025-10-26 01:52:27.827 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.347 seconds (success: True)
2025-10-26 01:52:29.820 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.339 seconds (success: True)
2025-10-26 01:52:31.825 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.343 seconds (success: True)
2025-10-26 01:52:33.829 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.348 seconds (success: True)
2025-10-26 01:52:35.830 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.349 seconds (success: True)
2025-10-26 01:52:37.831 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.351 seconds (success: True)
2025-10-26 01:52:39.827 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.346 seconds (success: True)
2025-10-26 01:52:41.827 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.346 seconds (success: True)
2025-10-26 01:52:43.830 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.350 seconds (success: True)
2025-10-26 01:52:45.837 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.356 seconds (success: True)
2025-10-26 01:52:47.829 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.348 seconds (success: True)
2025-10-26 01:52:49.831 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.351 seconds (success: True)
2025-10-26 01:52:51.820 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.339 seconds (success: True)
2025-10-26 01:52:53.811 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.330 seconds (success: True)
2025-10-26 01:52:55.809 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.328 seconds (success: True)
2025-10-26 01:52:57.808 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.327 seconds (success: True)
2025-10-26 01:52:59.797 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.316 seconds (success: True)
2025-10-26 01:53:01.797 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.316 seconds (success: True)
2025-10-26 01:53:03.792 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.312 seconds (success: True)
2025-10-26 01:53:05.798 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.318 seconds (success: True)
2025-10-26 01:53:07.794 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.312 seconds (success: True)
2025-10-26 01:53:09.804 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.322 seconds (success: True)
2025-10-26 01:53:10.830 ERROR (MainThread) [custom_components.keymaster.binary_sensor] Z-Wave integration not found
2025-10-26 01:53:11.797 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.316 seconds (success: True)
2025-10-26 01:53:12.530 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.402 seconds (success: True)
2025-10-26 01:53:14.828 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.340 seconds (success: True)
2025-10-26 01:53:16.828 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.347 seconds (success: True)
2025-10-26 01:53:18.827 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.347 seconds (success: True)
2025-10-26 01:53:20.829 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.349 seconds (success: True)
2025-10-26 01:53:22.827 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.347 seconds (success: True)
2025-10-26 01:53:24.826 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.346 seconds (success: True)
2025-10-26 01:53:26.819 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.339 seconds (success: True)
2025-10-26 01:53:28.819 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.337 seconds (success: True)
2025-10-26 01:53:30.808 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.327 seconds (success: True)
2025-10-26 01:53:32.803 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.321 seconds (success: True)
2025-10-26 01:53:34.791 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.311 seconds (success: True)
2025-10-26 01:53:36.792 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.309 seconds (success: True)
2025-10-26 01:53:38.885 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.404 seconds (success: True)
2025-10-26 01:53:40.878 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.397 seconds (success: True)
2025-10-26 01:53:42.877 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.397 seconds (success: True)
2025-10-26 01:53:44.867 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.387 seconds (success: True)
2025-10-26 01:53:46.859 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.379 seconds (success: True)
2025-10-26 01:53:48.856 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.375 seconds (success: True)
2025-10-26 01:53:50.853 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.373 seconds (success: True)
2025-10-26 01:53:52.848 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.367 seconds (success: True)
2025-10-26 01:53:54.840 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.360 seconds (success: True)
2025-10-26 01:53:56.838 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.358 seconds (success: True)
2025-10-26 01:53:58.820 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.338 seconds (success: True)
2025-10-26 01:53:59.445 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.391 seconds (success: True)
2025-10-26 01:54:01.841 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.360 seconds (success: True)
2025-10-26 01:54:03.829 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.348 seconds (success: True)
2025-10-26 01:54:05.832 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.351 seconds (success: True)
2025-10-26 01:54:07.819 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.338 seconds (success: True)
2025-10-26 01:54:09.805 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.324 seconds (success: True)
2025-10-26 01:54:11.806 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.325 seconds (success: True)
2025-10-26 01:54:13.798 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.316 seconds (success: True)
```

**Comment by danielcherubini** [comment]
Right, just finished a massive new feature.. i will look into this now!

**Comment by danielcherubini** [comment]
Fixed in 2.4.1

**Comment by Busted99** [comment]
That was fast! Thanks much!

**Comment by danielcherubini** [comment]
Anytime :D

**Comment by inventor7777** [comment]
@danielcherubini I also have this issue still, even on 2.4.3.

This results in very odd logs lol

![Image](https://github.com/user-attachments/assets/46523453-ad87-42cf-ba69-3b4eb9db4798)

````2025-11-10 18:57:40.606 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_status() got printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:40.733 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task task_id: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:40.733 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task: task from the api: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:40.733 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_current_task: Got task bf5475b9-9ed7-435b-b544-a7ad7305d8f1 (begin: 2025-11-11 00:31:47+00:00, end: 2025-11-11 02:28:00+00:00)
2025-11-10 18:57:40.734 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_printer_data() returning printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:40.734 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.377 seconds (success: True)
2025-11-10 18:57:42.651 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_status() got printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:42.807 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task task_id: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:42.808 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task: task from the api: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:42.808 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_current_task: Got task bf5475b9-9ed7-435b-b544-a7ad7305d8f1 (begin: 2025-11-11 00:31:47+00:00, end: 2025-11-11 02:28:00+00:00)
2025-11-10 18:57:42.808 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_printer_data() returning printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:42.808 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.452 seconds (success: True)
2025-11-10 18:57:44.597 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_status() got printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:44.747 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task task_id: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:44.747 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task: task from the api: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:44.748 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_current_task: Got task bf5475b9-9ed7-435b-b544-a7ad7305d8f1 (begin: 2025-11-11 00:31:47+00:00, end: 2025-11-11 02:28:00+00:00)
2025-11-10 18:57:44.748 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_printer_data() returning printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:44.748 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.391 seconds (success: True)
2025-11-10 18:57:45.964 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_status() got printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:46.093 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task task_id: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:46.093 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task: task from the api: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:46.093 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_current_task: Got task bf5475b9-9ed7-435b-b544-a7ad7305d8f1 (begin: 2025-11-11 00:31:47+00:00, end: 2025-11-11 02:28:00+00:00)
2025-11-10 18:57:46.094 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_printer_data() returning printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:46.094 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.408 seconds (success: True)
2025-11-10 18:57:46.729 DEBUG (MainThread) [custom_components.elegoo_printer] Sending printer video: {'status': <ElegooVideoStatus.SUCCESS: 0>, 'video_url': '192.168.50.122:3031/video'}
2025-11-10 18:57:46.729 DEBUG (MainThread) [custom_components.elegoo_printer] stream_source: Video is OK, getting stream source
2025-11-10 18:57:46.729 DEBUG (MainThread) [custom_components.elegoo_printer] stream_source: Using video url: http://192.168.50.122:3031/video
2025-11-10 18:57:47.593 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_status() got printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:47.735 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task task_id: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:47.735 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task: task from the api: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:47.736 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_current_task: Got task bf5475b9-9ed7-435b-b544-a7ad7305d8f1 (begin: 2025-11-11 00:31:47+00:00, end: 2025-11-11 02:28:00+00:00)
2025-11-10 18:57:47.736 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_printer_data() returning printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:47.736 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.379 seconds (success: True)
2025-11-10 18:57:49.602 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_status() got printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:49.739 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task task_id: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:49.739 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task: task from the api: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:49.739 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_current_task: Got task bf5475b9-9ed7-435b-b544-a7ad7305d8f1 (begin: 2025-11-11 00:31:47+00:00, end: 2025-11-11 02:28:00+00:00)
2025-11-10 18:57:49.739 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_printer_data() returning printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:49.740 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.383 seconds (success: True)
2025-11-10 18:57:50.658 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_status() got printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:50.785 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task task_id: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:50.785 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task: task from the api: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:50.785 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_current_task: Got task bf5475b9-9ed7-435b-b544-a7ad7305d8f1 (begin: 2025-11-11 00:31:47+00:00, end: 2025-11-11 02:28:00+00:00)
2025-11-10 18:57:50.786 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_printer_data() returning printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:50.786 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.414 seconds (success: True)
2025-11-10 18:57:52.568 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_status() got printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:52.728 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task task_id: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:52.728 DEBUG (MainThread) [custom_components.elegoo_printer.sdcp] get_printer_current_task: task from the api: bf5475b9-9ed7-435b-b544-a7ad7305d8f1
2025-11-10 18:57:52.728 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_current_task: Got task bf5475b9-9ed7-435b-b544-a7ad7305d8f1 (begin: 2025-11-11 00:31:47+00:00, end: 2025-11-11 02:28:00+00:00)
2025-11-10 18:57:52.728 DEBUG (MainThread) [custom_components.elegoo_printer] async_get_printer_data() returning printer_data (id: 281471526318544, status: ElegooMachineStatus.PRINTING)
2025-11-10 18:57:52.728 DEBUG (MainThread) [custom_components.elegoo_printer] Finished fetching Centauri Carbon data in 0.371 seconds (success: True)

**Comment by fxfitz** [comment]
@danielcherubini I can also confirm that this is still toggling chamber light in 2.4.3.

**Comment by fxfitz** [comment]
I threw up a PR, appears to work on my Home Assistant with my Centauri Carbon: https://github.com/danielcherubini/elegoo-homeassistant/pull/290
